// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// doubles
SEXP doubles();
RcppExport SEXP _altrepisode_doubles() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(doubles());
    return rcpp_result_gen;
END_RCPP
}
// doubles_example
SEXP doubles_example();
RcppExport SEXP _altrepisode_doubles_example() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(doubles_example());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_altrepisode_doubles", (DL_FUNC) &_altrepisode_doubles, 0},
    {"_altrepisode_doubles_example", (DL_FUNC) &_altrepisode_doubles_example, 0},
    {NULL, NULL, 0}
};

void init_altrep_classes(DllInfo* dll);
RcppExport void R_init_altrepisode(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_altrep_classes(dll);
}
