# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' lazy altrep version of abs
#'
#' @export
lazy_abs <- function(x) {
    .Call(`_altrepisode_lazy_abs`, x)
}

#' an altrep object that wraps a std::vector<double>
#'
#' @export
doubles <- function() {
    .Call(`_altrepisode_doubles`)
}

#' @export
doubles_example <- function() {
    .Call(`_altrepisode_doubles_example`)
}

